version: "3.7"
services:
  app:
    image: webclothingstore
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: clothingstore
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-tier-clothing

  # db:
  #   image: mysql:8.0
  #   container_name: dbwebshoes
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   command: --bind-address=0.0.0.0
  #   networks:
  #     - webshoes-app

  nginx:
    image: nginx:alpine
    container_name: nginxwebclothings
    restart: unless-stopped
    ports:
      - 8066:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker-compose/ssl:/etc/nginx/ssl
    networks:
      - app-tier-clothing
      
networks:
  app-tier-clothing:
    driver: bridge
